const VISIT_PAGE = 'VISIT_PAGE';
const BUY_PAGE = 'BUY_PAGE';
const PAYMENT_FAILURE = 'PAYMENT_FAILURE';
const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';

module.exports = {
  VISIT_PAGE,
  BUY_PAGE,
  PAYMENT_FAILURE,
  PAYMENT_SUCCESS
}
